$(arg device_name)_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbmove with shaft reference position and stiffness preset
$(arg device_name)_position_and_preset_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - $(arg device_name)_shaft_joint
    - $(arg device_name)_stiffness_preset_virtual_joint
  constraints:  # fake values due to the adaptability
    goal_time: 10.0
    stopped_velocity_tolerance: 10.0
    $(arg device_name)_shaft_joint:
      trajectory: 10.0
      goal: 10.0
    $(arg device_name)_stiffness_preset_virtual_joint:
      trajectory: 10.0
      goal: 10.0
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbmove with motor positions
$(arg device_name)_motor_positions_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - $(arg device_name)_motor_1_joint
    - $(arg device_name)_motor_2_joint
  constraints:  # fake values due to the adaptability
    goal_time: 10.0
    stopped_velocity_tolerance: 10.0
    $(arg device_name)_motor_1_joint:
      trajectory: 10.0
      goal: 10.0
    $(arg device_name)_motor_2_joint:
      trajectory: 10.0
      goal: 10.0
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0